# Generated by Django 3.2.5 on 2021-07-10 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('director', models.CharField(blank=True, max_length=250, null=True)),
                ('starring', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telegu', 'Telegu'), ('kannada', 'Kannada'), ('indian_bangla', 'Indian Bangla'), ('korean', 'Korean'), ('spanish', 'Spanish'), ('japanese', 'Japanese'), ('turkish', 'Turkish'), ('chinese', 'Chinese'), ('indonesian', 'Indonesian'), ('iranian', 'Iranian'), ('french', 'French'), ('german', 'German'), ('thai', 'Thai'), ('russian', 'Russian'), ('others', 'Others'), ('animation', 'Animation'), ('anime', 'Anime')], default='English', max_length=50, null=True)),
                ('runtime', models.CharField(blank=True, max_length=250, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=250, null=True)),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('trailer_link', models.CharField(blank=True, max_length=999, null=True)),
                ('watch_link', models.URLField(blank=True, max_length=999, null=True)),
                ('gdrive_quality_480p', models.URLField(blank=True, max_length=999, null=True)),
                ('gdrive_quality_720p', models.URLField(blank=True, max_length=999, null=True)),
                ('gdrive_quality_1080p', models.URLField(blank=True, max_length=999, null=True)),
                ('gdrive_quality_4K', models.URLField(blank=True, max_length=999, null=True)),
                ('gdrive_download_dual_audio', models.URLField(blank=True, max_length=999, null=True)),
                ('gdrive_download_hindi_dubbed', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_quality_480p', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_quality_720p', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_quality_1080p', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_quality_4K', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_download_dual_audio', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_download_hindi_dubbed', models.URLField(blank=True, max_length=999, null=True)),
                ('torrent', models.URLField(blank=True, max_length=999, null=True)),
                ('info1', models.CharField(blank=True, max_length=250, null=True)),
                ('info2', models.CharField(blank=True, max_length=250, null=True)),
                ('synopsys', models.TextField(blank=True, null=True)),
                ('subtitle_link', models.URLField(blank=True, max_length=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(blank=True, max_length=250, to='core.GenreModel')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TopSlideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SuperheroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwaresGamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(blank=True, choices=[('softwares', 'Softwares'), ('games', 'Games'), ('ebooks', 'eBooks'), ('tutorials', 'Tutorials')], default='Games', max_length=50, null=True)),
                ('platform', models.CharField(blank=True, choices=[('pc', 'PC'), ('android', 'Android'), ('console', 'Console')], default='PC', max_length=50, null=True)),
                ('rated', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('developer', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_sys_req', models.TextField(blank=True, null=True)),
                ('rec_sys_req', models.TextField(blank=True, null=True)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('gdrive_download_link', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_download_link', models.URLField(blank=True, max_length=999, null=True)),
                ('torrent', models.URLField(blank=True, max_length=999, null=True)),
                ('info1', models.CharField(blank=True, max_length=250, null=True)),
                ('info2', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(blank=True, max_length=250, to='core.GenreModel')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('director', models.CharField(blank=True, max_length=250, null=True)),
                ('starring', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telegu', 'Telegu'), ('kannada', 'Kannada'), ('indian_bangla', 'Indian Bangla'), ('korean', 'Korean'), ('spanish', 'Spanish'), ('japanese', 'Japanese'), ('turkish', 'Turkish'), ('chinese', 'Chinese'), ('indonesian', 'Indonesian'), ('iranian', 'Iranian'), ('french', 'French'), ('german', 'German'), ('thai', 'Thai'), ('russian', 'Russian'), ('others', 'Others'), ('animation', 'Animation'), ('anime', 'Anime')], default='English', max_length=50, null=True)),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=250, null=True)),
                ('trailer_link', models.CharField(blank=True, max_length=999, null=True)),
                ('info1', models.CharField(blank=True, max_length=250, null=True)),
                ('info2', models.CharField(blank=True, max_length=250, null=True)),
                ('synopsys', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ManyToManyField(blank=True, max_length=250, to='core.GenreModel')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('release_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('season_number', models.IntegerField(blank=True, default=1, null=True)),
                ('episode_count', models.IntegerField(blank=True, default=1, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seriesmodel')),
            ],
            options={
                'ordering': ('series__title',),
            },
        ),
        migrations.CreateModel(
            name='SatyajitRayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='OscarWinningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='JamesBondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='IMDBTopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HindiDubbedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('episode', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('runtime', models.CharField(blank=True, max_length=250, null=True)),
                ('watch_link', models.URLField(blank=True, max_length=999, null=True)),
                ('gdrive_download_link', models.URLField(blank=True, max_length=999, null=True)),
                ('onedrive_download_link', models.URLField(blank=True, max_length=999, null=True)),
                ('subtitle_link', models.URLField(blank=True, max_length=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seasonmodel')),
            ],
            options={
                'ordering': ('season',),
            },
        ),
        migrations.CreateModel(
            name='DualAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ClassicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('hollywood', 'Hollywood'), ('bollywood', 'Bollywood'), ('horror', 'Horror'), ('foreign', 'Foreign')], default='hollywood', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BSubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
        ),
    ]
