# Generated by Django 3.2.9 on 2022-03-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='still_path',
            field=models.TextField(blank=True, max_length=5555, null=True),
        ),
    ]
