# Generated by Django 3.2.9 on 2022-03-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_moviemodel_still_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodemodel',
            name='direct_download_alt1_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='direct_download_alt2_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='direct_download_main',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='gdrive_download_alt1_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='gdrive_download_alt2_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='gdrive_download_main',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='hevc_download_alt1_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='hevc_download_alt2_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='hevc_download_main',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='onedrive_download_alt1_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='onedrive_download_alt2_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='onedrive_download_main',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='subtitle_link',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='tmdb_thumbnail',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='watch_link_alt1_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='watch_link_alt2_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='watch_link_main_source',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='direct_download_1080p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='direct_download_480p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='direct_download_4K',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='direct_download_720p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='direct_download_dual_audio',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='direct_download_hindi_dubbed',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='gdrive_download_dual_audio',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='gdrive_download_hindi_dubbed',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='gdrive_quality_1080p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='gdrive_quality_480p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='gdrive_quality_4K',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='gdrive_quality_720p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='hevc_download_dual_audio',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='hevc_download_hindi_dubbed',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='hevc_quality_1080p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='hevc_quality_4K',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='hevc_quality_720p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='onedrive_download_dual_audio',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='onedrive_download_hindi_dubbed',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='onedrive_quality_1080p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='onedrive_quality_480p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='onedrive_quality_4K',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='onedrive_quality_720p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='subtitle_link',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='tmdb_poster',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='tmdb_thumbnail',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='torrent',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='watch_link_alt1_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='watch_link_alt2_url',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='watch_link_main_source',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='download_full_download_dual_audio',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='download_full_download_hindi_dubbed',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='download_full_quality_1080p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='download_full_quality_480p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='download_full_quality_720p',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='tmdb_poster',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='tmdb_thumbnail',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='softwaresgamesmodel',
            name='direct_download',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='softwaresgamesmodel',
            name='gdrive_download_link',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='softwaresgamesmodel',
            name='onedrive_download_link',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='softwaresgamesmodel',
            name='torrent',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
