# Generated by Django 3.2.7 on 2021-09-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210915_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bsubmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='classicmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='dualaudiomodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='hindidubbedmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='imdbtopmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='jamesbondmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='oscarwinningmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='satyajitraymodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='softwaresgamesmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='superheromodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='topslidemodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='topslidemodel',
            name='series_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seriesmodel'),
        ),
        migrations.AlterField(
            model_name='topslidemodel',
            name='movie_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel'),
        ),
    ]
