# Generated by Django 3.2.7 on 2021-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210916_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='direct_download',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='direct_download_1080p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='direct_download_480p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='direct_download_4K',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='direct_download_720p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='direct_download_dual_audio',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='direct_download_hindi_dubbed',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
