# Generated by Django 3.2.7 on 2021-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210916_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='writers',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='writers',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
