# Generated by Django 3.2.7 on 2021-09-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210916_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='tmdb_poster',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='tmdb_thumbnail',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
