# Generated by Django 3.2.7 on 2021-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210925_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
