# Generated by Django 3.2.9 on 2022-01-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220112_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='mega_download_dual_audio',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='mega_download_hindi_dubbed',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='mega_quality_1080p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='mega_quality_480p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='mega_quality_4K',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='mega_quality_720p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
