# Generated by Django 3.2.9 on 2022-01-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220112_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='watch_link_others_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
