# Generated by Django 3.2.9 on 2022-01-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_moviemodel_watch_link_others_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='watch_link_english',
            new_name='watch_link_main_source',
        ),
    ]
