# Generated by Django 3.2.9 on 2022-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_watch_link_english_moviemodel_watch_link_main_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='watch_link_hindi',
            new_name='watch_link_alt1_url',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='watch_link_others',
            new_name='watch_link_alt2_url',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='watch_link_others_name',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='watch_link_alt1_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='watch_link_alt2_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
