# Generated by Django 3.2.9 on 2022-02-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220116_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodemodel',
            old_name='watch_link',
            new_name='watch_link_main_source',
        ),
    ]
