# Generated by Django 3.2.9 on 2022-02-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_watch_link_episodemodel_watch_link_main_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodemodel',
            name='direct_download_alt1_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='direct_download_alt1_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='direct_download_alt2_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='direct_download_alt2_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='gdrive_download_alt1_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='gdrive_download_alt1_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='gdrive_download_alt2_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='gdrive_download_alt2_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='mega_download_alt1_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='mega_download_alt1_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='mega_download_alt2_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='mega_download_alt2_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='mega_download_link',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='onedrive_download_alt1_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='onedrive_download_alt1_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='onedrive_download_alt2_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='onedrive_download_alt2_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='watch_link_alt1_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='watch_link_alt1_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='watch_link_alt2_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='watch_link_alt2_url',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
