# Generated by Django 3.2.9 on 2022-02-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220201_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodemodel',
            old_name='direct_download',
            new_name='direct_download_main',
        ),
        migrations.RenameField(
            model_name='episodemodel',
            old_name='gdrive_download_link',
            new_name='gdrive_download_main',
        ),
        migrations.RenameField(
            model_name='episodemodel',
            old_name='mega_download_link',
            new_name='mega_download_main',
        ),
        migrations.RenameField(
            model_name='episodemodel',
            old_name='onedrive_download_link',
            new_name='onedrive_download_main',
        ),
    ]
