# Generated by Django 3.2.9 on 2022-02-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_moviemodel_mega_quality_480p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodemodel',
            old_name='mega_download_alt1_name',
            new_name='hevc_download_alt1_name',
        ),
        migrations.RenameField(
            model_name='episodemodel',
            old_name='mega_download_alt1_url',
            new_name='hevc_download_alt1_url',
        ),
        migrations.RenameField(
            model_name='episodemodel',
            old_name='mega_download_alt2_name',
            new_name='hevc_download_alt2_name',
        ),
        migrations.RenameField(
            model_name='episodemodel',
            old_name='mega_download_alt2_url',
            new_name='hevc_download_alt2_url',
        ),
        migrations.RenameField(
            model_name='episodemodel',
            old_name='mega_download_main',
            new_name='hevc_download_main',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='mega_download_dual_audio',
            new_name='hevc_download_dual_audio',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='mega_download_hindi_dubbed',
            new_name='hevc_download_hindi_dubbed',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='mega_quality_1080p',
            new_name='hevc_quality_1080p',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='mega_quality_4K',
            new_name='hevc_quality_4K',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='mega_quality_720p',
            new_name='hevc_quality_720p',
        ),
    ]
