# Generated by Django 3.2.9 on 2022-02-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220209_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmodel',
            name='download_full_download_dual_audio',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='seasonmodel',
            name='download_full_download_hindi_dubbed',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='seasonmodel',
            name='download_full_quality_1080p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='seasonmodel',
            name='download_full_quality_480p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='seasonmodel',
            name='download_full_quality_720p',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
