# Generated by Django 3.2.9 on 2022-02-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220211_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodemodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='seasonmodel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='softwaresgamesmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
