# Generated by Django 3.2.9 on 2022-02-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220215_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
