# Generated by Django 3.2.9 on 2022-02-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_seasonmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSubmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('subscene_url', models.URLField()),
                ('profile_pic', models.ImageField(null=True, upload_to='submaker_profile/')),
            ],
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='bsubmaker',
            field=models.ManyToManyField(blank=True, to='core.BSubmaker'),
        ),
    ]
