# Generated by Django 3.2.9 on 2022-02-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220219_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsubmaker',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='submaker_profile/'),
        ),
        migrations.AlterField(
            model_name='bsubmaker',
            name='subscene_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
