# Generated by Django 3.2.9 on 2022-02-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_bsubmaker_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BSubmaker',
            new_name='BsubCreatorModel',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='bsubmaker',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='bsub_creator',
            field=models.ManyToManyField(blank=True, to='core.BsubCreatorModel'),
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='bsub_creator',
            field=models.ManyToManyField(blank=True, to='core.BsubCreatorModel'),
        ),
    ]
