# Generated by Django 3.2.9 on 2022-05-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_linkcategory_linksubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkcategory',
            name='content',
        ),
        migrations.AlterField(
            model_name='linksubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linksubcat', to='core.linkcategory'),
        ),
        migrations.CreateModel(
            name='LinkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linksource', to='core.moviemodel')),
            ],
        ),
        migrations.AddField(
            model_name='linkcategory',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkcat', to='core.linksource'),
        ),
    ]
