# Generated by Django 3.2.9 on 2022-05-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220504_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moviemodel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
