# Generated by Django 3.2.9 on 2022-05-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_footagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='type',
            field=models.CharField(choices=[('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telegu', 'Telegu'), ('kannada', 'Kannada'), ('indian_bangla', 'Indian Bangla'), ('korean', 'Korean'), ('spanish', 'Spanish'), ('japanese', 'Japanese'), ('turkish', 'Turkish'), ('chinese', 'Chinese'), ('indonesian', 'Indonesian'), ('iranian', 'Iranian'), ('french', 'French'), ('german', 'German'), ('thai', 'Thai'), ('russian', 'Russian'), ('documentary', 'Documentary'), ('others', 'Others'), ('animation', 'Animation'), ('anime', 'Anime')], default='English', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('tamil', 'Tamil'), ('telegu', 'Telegu'), ('kannada', 'Kannada'), ('indian_bangla', 'Indian Bangla'), ('korean', 'Korean'), ('spanish', 'Spanish'), ('japanese', 'Japanese'), ('turkish', 'Turkish'), ('chinese', 'Chinese'), ('indonesian', 'Indonesian'), ('iranian', 'Iranian'), ('french', 'French'), ('german', 'German'), ('thai', 'Thai'), ('russian', 'Russian'), ('documentary', 'Documentary'), ('others', 'Others'), ('animation', 'Animation'), ('anime', 'Anime')], default='English', max_length=50, null=True),
        ),
    ]
