# Generated by Django 3.2.9 on 2022-08-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220511_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkEpisodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('category',),
            },
        ),
        migrations.AlterModelOptions(
            name='linkcategory',
            options={'ordering': ('category',)},
        ),
        migrations.AlterModelOptions(
            name='linksource',
            options={'ordering': ('source',)},
        ),
        migrations.AlterModelOptions(
            name='linksubcategory',
            options={'ordering': ('subcategory',)},
        ),
        migrations.CreateModel(
            name='LinkEpisodeSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linksubcat', to='core.linkepisodecategory')),
            ],
            options={
                'ordering': ('subcategory',),
            },
        ),
        migrations.CreateModel(
            name='LinkEpisodeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linksource', to='core.episodemodel')),
            ],
            options={
                'ordering': ('source',),
            },
        ),
        migrations.AddField(
            model_name='linkepisodecategory',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkcat', to='core.linkepisodesource'),
        ),
    ]
