# Generated by Django 3.2.9 on 2022-08-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220808_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkepisodecategory',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkepisodecat', to='core.linkepisodesource'),
        ),
        migrations.AlterField(
            model_name='linkepisodesource',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkepisodesource', to='core.episodemodel'),
        ),
        migrations.AlterField(
            model_name='linkepisodesubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linkepisodesubcat', to='core.linkepisodecategory'),
        ),
    ]
