# Generated by Django 3.2.9 on 2022-08-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20220813_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='hevc_download_dual_audio',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='hevc_download_hindi_dubbed',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='hevc_quality_1080p',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='hevc_quality_4K',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='hevc_quality_720p',
        ),
    ]
